### ISSUE TITLE
PYNBS does not work as intended

### ISSUE THREAD

**Issue by charlie-sans** [vberlier/pynbs#32]
**Describe the bug**

when using pynbs thru `pip install pynbs` and thru a clean download off the GitHub

anytime I try to import it or do anything with it, I get a multitude of errors out from the console

**Expectedbehaviourr**
for it to work as intended as stated on the GitHub repo

**Comment by charlie-sans** [comment]
i hope this is the right place for it

**Comment by Bentroen** [comment]
Thanks for reporting the issue! Could you please show the error you're getting?

**Comment by charlie-sans** [comment]
sorry for the late reply! i have managed to get it to work, had the github source version of it within my project dir and it was calling that and the pip one aswell, it was freaking out because it found 2 and couldnt choose!
